const LOGIN = "LOGIN"
const LOGOUT = "LOGOUT"
const TOGGLE_SELECTION = "TOGGLE_SELECTION"
const TOGGLE_VISIBILITY = "TOGGLE_VISIBILITY"
const INCREMENT_WEIGHT = "INCREMENT_WEIGHT"
const DECREMENT_WEIGHT = "DECREMENT_WEIGHT"
const TOGGLE_DECISION = "TOGGLE_DECISION"

const actions = {
    LOGIN,
    LOGOUT,
    TOGGLE_SELECTION,
    TOGGLE_VISIBILITY,
    INCREMENT_WEIGHT,
    DECREMENT_WEIGHT,
    TOGGLE_DECISION
}

export default actions